#                     Copyright H Dub (hdub-tech) 2026
#        Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE or copy at https://www.boost.org/LICENSE_1_0.txt
#                     Kali template - Version 4.0

# Parse defaults and overrides file, if existing.
require 'yaml'
defaults = YAML.load_file('defaults.yml')
overrides_file = 'overrides.yml'
overrides = File.exist?(overrides_file) ? YAML.load_file(overrides_file) : {}

Vagrant.configure("2") do |config|

  vm_name = overrides['vm_name'] || defaults['vm_name']

  # Name the VM specifically
  config.vm.define vm_name do |kali|
    # Official Kali image
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = overrides['hostname'] || defaults['hostname']
    kali.vm.synced_folder overrides['local_shared_dir'] || defaults['local_shared_dir'], "/vagrant"
    if overrides['bridged_adapter'] && overrides['bridged_adapter'] != "disabled" then
      kali.vm.network "public_network", bridge: overrides['bridged_adapter'] || defaults['bridged_adapter']
    end

    # VirtualBox configuration
    kali.vm.provider "virtualbox" do |vb|
      # Name in VirtualBox
      vb.name = vm_name
      # Disable Remote Display server ffs Kali
      vb.customize ["modifyvm", :id, "--vrde=off"]
    end

    # Install requested apt packages and fix grub-pc
    apt_packages = overrides['apt_packages'] || defaults['apt_packages']
    kali.vm.provision "Install specified apt packages #{apt_packages} and Python dependency packages", type: "shell", privileged: true, inline: <<~APT_SCRIPT
      # Update Kali keyring
      wget https://archive.kali.org/archive-keyring.gpg -O /usr/share/keyrings/kali-archive-keyring.gpg

      # Set grub install device for grub-pc updates
      # Find the partition grub is on (tail cuz can't surpress header), trim
      # off the partition ID so we have just the disk, and make sure just one
      boot_disk=$( df --output=source /boot/grub | tail -n1 | grep --color=no -m1 -o "[^0-9]*" | head -n1 )
      echo "grub-pc grub-pc/install_devices multiselect $boot_disk" | debconf-set-selections -v

      # Non-interactive flags
      export DEBIAN_FRONTEND=noninteractive
      # https://debian-handbook.info/browse/stable/sect.package-meta-information.html#sidebar.questions-conffiles
      # Use default confs or old confs
      apt_dpkg_opts="-o Dpkg::Options::=\"--force-confdef\" -o Dpkg::Options::=\"--force-confold\""

      # Run apt
      apt-get update
      apt-get --yes $apt_dpkg_opts upgrade
      apt-get --yes install #{apt_packages.join(' ')} \
                            curl git gcc make zlib1g-dev libssl-dev libffi-dev libsqlite3-dev \
                            libbz2-dev libreadline-dev liblzma-dev
    APT_SCRIPT

    # Preferred shell - need to update before modifying settings in rc files
    run_as_root = overrides['run_as_root'] || defaults['run_as_root']
    primary_user = run_as_root ? 'root' : 'vagrant'
    preferred_shell = overrides['preferred_shell'] || defaults['preferred_shell']
    kali.vm.provision "Set #{primary_user}'s preferred shell to #{preferred_shell}", type: "shell", privileged: true, inline: "chsh -s /usr/bin/#{preferred_shell} #{primary_user}"

    # Install and setup pyenv
    pyenvrc_file = "/etc/profile.d/pyenvrc"
    kali.vm.provision "Install and setup pyenv", type: "shell", privileged: run_as_root, inline: <<~PYENV_SETUP_SCRIPT
      set -e
      # Install pyenv if not already there
      if [ ! -e ~/.pyenv ]; then
        # Split up due to noisy unnecessary stderr on both commands
        curl --silent --output /tmp/pyenv.run https://pyenv.run
        bash /tmp/pyenv.run 2>&1
      else
        echo "WARNING: ~/.pyenv exists - Skipping pyenv installation" 1>&2
      fi
	# The BASH Heredocs must use tabs: https://www.shellcheck.net/wiki/SC1040
        echo "INFO: Creating #{pyenvrc_file} to be sourced in ~/.#{preferred_shell}rc with contents:"
	cat <<-'PYRC' | sudo tee #{pyenvrc_file}  # Deliberate no -a
		export PYENV_ROOT="$HOME/.pyenv"
		[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
		eval "$(pyenv init - bash)"
	PYRC
      echo "INFO: Adding ". #{pyenvrc_file}" to ~/.#{preferred_shell}rc and ~/.profile, only if not already there"
      if ! grep -q #{pyenvrc_file} ~/.#{preferred_shell}rc; then echo ". #{pyenvrc_file}" | tee -a ~/.#{preferred_shell}rc; fi
      if ! grep -q #{pyenvrc_file} ~/.profile; then echo ". #{pyenvrc_file}" | tee -a ~/.profile; fi
    PYENV_SETUP_SCRIPT

    # Install specified Python version using pyenv and set as global default
    python_version = overrides['python_version'] || defaults['python_version']
    pip_packages = overrides['pip_packages'] || defaults['pip_packages']
    kali.vm.provision "Install Python #{python_version}, set as global default version and install #{pip_packages}", type: "shell", privileged: run_as_root, inline: <<~PYENV_INSTALL_SCRIPT
      set -e
      . #{pyenvrc_file}
      pyenv install --skip-existing #{python_version} 2>&1
      pyenv global #{python_version}
      pip install -U pip pipx #{pip_packages.join(' ')}
    PYENV_INSTALL_SCRIPT

    # Clone specified git repos, if specified
    git_repos_dir = overrides['git_repos_dir'] || defaults['git_repos_dir']
    git_repos = overrides['git_repos'] || defaults['git_repos']
    if git_repos.length > 0
      kali.vm.provision "Cloning specified git_repos to #{git_repos_dir}", type: "shell", privileged: run_as_root, inline: <<~GIT_REPOS_SCRIPT
        set -e
        clone_needs_sudo=""
        if [ -d #{git_repos_dir} ]; then
          user_writable_git_dir=$( find #{git_repos_dir} -maxdepth 0 -writable )
          if [ "#{git_repos_dir}" != "$user_writable_git_dir" ]; then
            clone_needs_sudo="sudo"
          fi
        else
          mkdir #{git_repos_dir}
        fi
        cd #{git_repos_dir}
        for url in `echo #{git_repos.join(' ')}`; do
          project_dir=${url##http*/}
          echo "INFO: Cloning $url to #{git_repos_dir}/$project_dir..."
          if [ ! -d $project_dir ]; then
            $clone_needs_sudo git clone $url
            if (("${#clone_needs_sudo}" > 0)); then sudo chown -R #{primary_user} $project_dir; fi
          else
            echo "WARNING: $project_dir already exists - skipping" 1>&2
          fi
        done
      GIT_REPOS_SCRIPT
    end

    # pipx install specified projects, if specified
    pipx_projects = overrides['pipx_projects'] || defaults['pipx_projects']
    apps_dir = overrides['apps_dir'] || defaults['apps_dir']
    if pipx_projects.length > 0
      # TODO make more efficient as bash loop
      pipx_projects.each do |path|
        kali.vm.provision "pipx installing #{path}", type: "shell", privileged: run_as_root, inline: <<~PIPX_INSTALL_SCRIPT
          set -e
          . #{pyenvrc_file}
          git_repos_dir=#{git_repos_dir}
          apps_dir=#{apps_dir}
          pipx install #{path}
        PIPX_INSTALL_SCRIPT
      end

      # pipx ensurepath + vagrant seems to need special su work to get it to update a non-default shell for root.
      kali.vm.provision "Running pipx ensurepath for #{primary_user}", type: "shell", privileged: true, inline: "su -l #{primary_user} -c \"pipx ensurepath\""
    end

    # curl | bash install specified projects, if specified
    curl_bash_projects = overrides['curl_bash_projects'] || defaults['curl_bash_projects']
    if curl_bash_projects.length > 0
      # TODO make more efficient as bash loop
      curl_bash_projects.each do |url|
        kali.vm.provision "curl|bash installing #{url}", type: "shell", privileged: run_as_root, inline: <<~CURL_BASH_INSTALL_SCRIPT
          set -e
          curl "#{url}" | bash
        CURL_BASH_INSTALL_SCRIPT
      end
    end

    # Decompress various downloaded apps
    compressed_app_urls = overrides['compressed_app_urls'] || defaults['compressed_app_urls']
    if compressed_app_urls.length > 0
      # TODO make more efficient as bash loop
      compressed_app_urls.each do |compressed_app_url|
        kali.vm.provision "Downloading #{compressed_app_url['url']} to #{apps_dir} and extracting/dpkg installing", type: "shell", privileged: run_as_root, inline: <<~WGET_EXTRACT
          set -e
          if [ ! -d "#{apps_dir}" ]; then
            mkdir --parents "#{apps_dir}"
            chown --recursive "#{primary_user}" "#{apps_dir}"
          fi

          cd "#{apps_dir}"
          compressed_file=$( basename "#{compressed_app_url['url']}" )
          if [ ! -f "#{apps_dir}/${compressed_file}" ]; then
            sudo wget --no-verbose "#{compressed_app_url['url']}"
            # Checksum validation, if provided
            if [[ -n "#{compressed_app_url['checksum']}" && -n "#{compressed_app_url['algorithm']}" ]]; then
              algorithm="#{compressed_app_url['algorithm']}"
              checksum_file="${compressed_file}.${algorithm}"
              echo "#{compressed_app_url['checksum']} $compressed_file" | sudo tee $checksum_file
              sudo cksum --algorithm $algorithm --check $checksum_file
            fi
            project_dir=
            case "$compressed_file" in
              *.zip)
                project_dir=$( unzip -lq $compressed_file | head -n3 | tail -n1 | awk '{print $4}' | cut -d\/ -f1 )
                sudo unzip -q $compressed_file
                ;;
              *.tar.gz)
                project_dir=$( tar tf $compressed_file | head -n1 )
                sudo tar xzf $compressed_file
                ;;
              *.deb)
                sudo dpkg --install $compressed_file
                ;;
              *) echo "WARNING: #{compressed_app_url['url']} has an unsupported extension. Downloaded only!" ;;
            esac
            # Only chown if has $project_dir
            if [ -n "$project_dir" ]; then
              sudo chown -R #{primary_user} "$project_dir"
            fi
          else
            echo "WARNING: #{apps_dir}/$compressed_file already exists - skipping" 1>&2
          fi
        WGET_EXTRACT
      end
    end

    # Add shortcuts
    kali.vm.provision "Copy in shortcut files", type: "file", source: "shortcuts/.", destination: "~/Desktop"
    # Set ONLY the shortcuts we created as "secure"
    Dir.glob("shortcuts/*.desktop") do |s|
      shortcut = File.basename(s)
      kali.vm.provision "Set copied shortcut #{shortcut} to 'secure'", type: "shell", privileged: run_as_root, inline: <<~SECURE_SHORTCUTS
        set -e
        shortcut_path=~/Desktop/"#{shortcut}"
        sed -i'' -e "s|\\$apps_dir|#{apps_dir}|" -e "s|\\$git_repos_dir|#{git_repos_dir}|" $shortcut_path
        gio set -t string $shortcut_path metadata::xfce-exe-checksum "$( sha256sum "$shortcut_path" | awk '{print $1}')"
      SECURE_SHORTCUTS
    end

    # Run custom specific setup script
    custom_setup_script = overrides['custom_setup_script'] || defaults['custom_setup_script']
    if !custom_setup_script.empty?
      kali.vm.provision "Run custom setup script", type: "shell", privileged: run_as_root, inline: <<~SETUP_SCRIPT
        git_repos_dir=#{git_repos_dir}
        apps_dir=#{apps_dir}
        #{custom_setup_script}
        echo "INFO: Copying this script to the shared directory in case it needs to be run again, excluding this comment/cmd"
        cat /tmp/vagrant-shell | head -n -2 | sed -e '1i#!/usr/bin/env bash' | tee /vagrant/vagrant-custom-setup.sh  # delib no -a
      SETUP_SCRIPT
    end
  end
end
